<!-- wp:heading {"level":1} -->
<h1>
		Chetan Kumar 
	</h1>
<!-- /wp:heading -->

<!-- wp:heading -->
<h2>
		WEB DEVELOPER
	</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3>
		EDUCATION
	</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa repellendus adipisci laborum placeat delectus labore cupiditate deserunt minus numquam consequatur esse, hic at earum illo animi eaque et, dolorem quo qui eos? Quam rerum possimus maxime veniam aut ratione eveniet aliquid cumque aspernatur ipsum libero quaerat, nam. Ad, sunt, error!</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3>
		EXPERIENCE
	</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa repellendus adipisci laborum placeat delectus labore cupiditate deserunt minus numquam consequatur esse, hic at earum illo animi eaque et, dolorem quo qui eos? Quam rerum possimus maxime veniam aut ratione eveniet aliquid cumque aspernatur ipsum libero quaerat, nam. Ad, sunt, error!
		40
</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":5} -->
<h5>
		HOURS PER WEEK
	</h5>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>
		101,410
</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":5} -->
<h5>
		LINES OF CODE
	</h5>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>
		8,210
</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":5} -->
<h5>
		GIT COMMITS
	</h5>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>
		406,840
</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":5} -->
<h5>
		WORDPRESS DOWNLOADS
	</h5>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3>
		SOME OF MY PROJECTS
	</h3>
<!-- /wp:heading -->

<!-- wp:heading {"level":5} -->
<h5>
		AWESOME WORKS THAT I'VE CONTRIBUTED TO. PROUDLY!
	</h5>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3>
		WHAT CLIENTS SAY?
	</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><strong>"Lacinia neque platea ipsum amet est odio aenean id quisque."</strong><strong>-&nbsp;KELLY MURRY</strong>ACME&nbsp;Inc.		
			</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>"Aliquam congue lacinia turpis proin sit nulla mattis semper."</strong><strong>-&nbsp;JEREMY LARSON</strong>ACME&nbsp;Inc.		
			</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>"Fermentum habitasse tempor sit et rhoncus, a morbi ultrices!"</strong><strong>-&nbsp;ERIC HART</strong>ACME&nbsp;Inc.</p>
<!-- /wp:paragraph -->
